config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'movies#index'

  resources :genres, except: %i[edit update]

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favourites, only: %i[create destroy]
  end

  resource :session, only: %i[new create destroy]
  get 'signin' => 'sessions#new'

  resources :users
  get 'signup' => 'users#new'
end

app/models/genre.rb
# frozen_string_literal: true

# Genre model logic
class Genre < ApplicationRecord
  before_save :set_params

  validates :name, presence: true, uniqueness: true

  has_many :characterizations, dependent: :destroy
  has_many :movies, through: :characterizations

  def to_param
    slug
  end

  private

  def set_params
    self.slug = name.parameterize
  end
end

app/controllers/genres_controller.rb
# frozen_string_literal: true

# GenresController
class GenresController < ApplicationController
  before_action :require_admin, except: %i[index show]
  before_action :find_genre_by_slug, only: %i[show destroy]

  def index
    @genres = Genre.order(:name)
  end

  def show
    @movies = @genre.movies
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to genres_url,
                  notice: 'Genre was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy
    redirect_to genres_url
  end

  private

  def find_genre_by_slug
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
# frozen_string_literal: true

# GenresHelper
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %>
  <%= render "shared/errors", object: genre %>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<% if @genres.present? %>
  <table class="table table-mb-4">
    <tbody>
      <th>Genre</th>
      <th>Number of movies</th>
      <% if current_user_admin? %>
        <th>Action</th>
      <% end %>
    <% @genres.each do | genre | %>
      <tr>
        <td><%= link_to genre.name, genre %></td>
        <td><%= genre.movies.size %></td>
        <% if current_user_admin? %>
          <td><%= button_to "Delete", genre, class: "btn btn-outline-danger btn-sm", method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% if current_user_admin? %>
<section class="admin">
  <%= link_to "Add Genre", new_genre_path, class: "button" %>
</section>
<% end %>

app/views/genres/new.html.erb
<h1>Create a new Genre</h1>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name.capitalize %> Movies</h1>
<% if @movies.present? %>
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-lg-2 mb-3 d-flex align-items-stretch">
        <div class="card">
          <div class="image">
            <%= main_image(movie) %>
          </div>
          <div class="card-body">
            <% if movie.released_on < Time.now %>
              <h6 class="card-title"><%= link_to movie.title, movie %></h6>
              <p class="card-text"><%= movie.released_on.to_fs(:rfc822) %></p>
            <% else %>
              <h6 class="card-title">Not released yet.</h6>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <p>No movies for this genre yet. <%= link_to "Why not add some?", signin_path %></p>
  <% end %>