config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'movies#index'

  resources :genres, except: %i[edit update]

  get 'movies/filter/:filter' => 'movies#index', as: :filtered_movies

  resources :movies do
    resources :reviews
    resources :favourites, only: %i[create destroy]
  end

  resource :session, only: %i[new create destroy]
  get 'signin' => 'sessions#new'

  resources :users
  get 'signup' => 'users#new'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer py-3 mt-auto bg-light">
  <div class="container">
    <span>Copyright &copy; <%= Time.now.year %> <a href="https://github.com/BitKoda">BitKoda</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li><%= nav_link_to "Released", movies_path %></li>
      <li><%= nav_link_to "Upcoming", filtered_movies_path(:upcoming) %></li>
      <li><%= nav_link_to "Hits", filtered_movies_path(:hits) %></li>
      <li><%= nav_link_to "Flops", filtered_movies_path(:flops) %></li>
      <li><%= nav_link_to "Users", users_path %></li>
      <li><%= nav_link_to "Genres", genres_path %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to "Account Settings", edit_user_path(current_user) %></li>
        <li><%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button" %></li>
      <% else %>
        <li><%= link_to "Sign In", signin_path, class: "button" %></li>
        <li><%= link_to "Sign Up", signup_path, class: "button" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
      <%= render "layouts/header" %>

      <div class="content">
        <%= render "layouts/flash" %>
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>